package com.zzvc.mmps.model;

// Generated 2010-10-22 15:04:15 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.TreeSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Sort;
import org.hibernate.annotations.SortType;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name = "player")
@Indexed
public class Player implements java.io.Serializable {

	private Long id;
	private String address;
	private String name;
	private Date lastHeartbeat;
	private Boolean enabled;
	private Set<PlayerKey> playerKeies = new TreeSet<PlayerKey>();

	public Player() {
	}

	public Player(String address, String name, Date lastHeartbeat,
			Boolean enabled, Set<PlayerKey> playerKeies) {
		this.address = address;
		this.name = name;
		this.lastHeartbeat = lastHeartbeat;
		this.enabled = enabled;
		this.playerKeies = playerKeies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@DocumentId
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "address")
	@Field
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "name")
	@Field
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_heartbeat", length = 0)
	public Date getLastHeartbeat() {
		return this.lastHeartbeat;
	}

	public void setLastHeartbeat(Date lastHeartbeat) {
		this.lastHeartbeat = lastHeartbeat;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "player_player_key", joinColumns = { @JoinColumn(name = "player_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "player_key_id", nullable = false, updatable = false) })
	@Cascade(CascadeType.ALL)
	@Sort(type=SortType.NATURAL)
	public Set<PlayerKey> getPlayerKeies() {
		return this.playerKeies;
	}

	public void setPlayerKeies(Set<PlayerKey> playerKeies) {
		this.playerKeies = playerKeies;
	}

}
