package com.zzvc.mmps.model;

// Generated 2011-4-11 11:22:00 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Server generated by hbm2java
 */
@Entity
@Table(name = "server")
public class Server implements java.io.Serializable {

	private Long id;
	private String code;
	private Boolean enabled;
	private Boolean started;
	private Date startupTime;
	private Date shutdownTime;
	private Date lastHeartbeat;
	private String lastConnectAddress;
	private String name;

	public Server() {
	}

	public Server(Long id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public Server(Long id, String code, Boolean enabled, Boolean started,
			Date startupTime, Date shutdownTime, Date lastHeartbeat,
			String lastConnectAddress, String name) {
		this.id = id;
		this.code = code;
		this.enabled = enabled;
		this.started = started;
		this.startupTime = startupTime;
		this.shutdownTime = shutdownTime;
		this.lastHeartbeat = lastHeartbeat;
		this.lastConnectAddress = lastConnectAddress;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "started")
	public Boolean getStarted() {
		return this.started;
	}

	public void setStarted(Boolean started) {
		this.started = started;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startup_time", length = 23)
	public Date getStartupTime() {
		return this.startupTime;
	}

	public void setStartupTime(Date startupTime) {
		this.startupTime = startupTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shutdown_time", length = 23)
	public Date getShutdownTime() {
		return this.shutdownTime;
	}

	public void setShutdownTime(Date shutdownTime) {
		this.shutdownTime = shutdownTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_heartbeat", length = 23)
	public Date getLastHeartbeat() {
		return this.lastHeartbeat;
	}

	public void setLastHeartbeat(Date lastHeartbeat) {
		this.lastHeartbeat = lastHeartbeat;
	}

	@Column(name = "last_connect_address")
	public String getLastConnectAddress() {
		return this.lastConnectAddress;
	}

	public void setLastConnectAddress(String lastConnectAddress) {
		this.lastConnectAddress = lastConnectAddress;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
